# Loading Data

In [ ]:
start = 0
end = 100_000
epochs = 10

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords

from tqdm import tqdm
from tqdm.notebook import tqdm_notebook

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/Dataset/train_clean.csv')
#test = pd.read_csv('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/Dataset/test_clean.csv')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2868897 entries, 0 to 2868896
Data columns (total 2 columns):
 #   Column          Dtype 
---  ------          ----- 
 0   BROWSE_NODE_ID  int64 
 1   TEXT            object
dtypes: int64(1), object(1)
memory usage: 43.8+ MB


In [ ]:
#test.info()

In [ ]:
train.isnull().sum()

BROWSE_NODE_ID    0
TEXT              0
dtype: int64

In [ ]:
#test.isnull().sum()

# Split data

In [ ]:
x, y = train['TEXT'].values, train['BROWSE_NODE_ID'].values

In [ ]:
x.shape,y.shape

((2868897,), (2868897,))

In [ ]:
del(train)

In [ ]:
#x_test = test['TEXT'].values

# Visualizing and making

In [ ]:
x[:3]

array(['pete cat bedtime blue doll inch pete cat coolest popular cat town new pete cat bedtime blue doll merrymaker rock striped red slipper one sleepy cat ready cuddle measure inch tall safe age removable clothing surface wash new pete cat bedtime blue plush doll based popular pete cat book james dean super cuddly ready naptime bedtime safe age perfect age measure inch merrymaker',
       'new yorker nyhm refrigerator magnet new yorker handsome cello wrapped hard magnet measure inch width inch height highlight one many beautiful new yorker cover full color cat tea cup new yorker cover artist gurbuz dogan eksioglu cat tea cup new yorker cover artist gurbuz dogan eksioglu handsome cello wrapped hard magnet ideal home office gift new yorker magazine lover highlight one many beautiful new yorker cover full color rigid magnet measure inch width inch height new yorker',
       'ultimate self sufficiency handbook complete guide baking craft gardening preserving harvest raising animal skyhors

In [ ]:
y[:3]

array([0, 1, 2])

In [ ]:
'''unique, counts = np.unique(y, return_counts=True)

print(np.asarray((unique, counts)))'''

'unique, counts = np.unique(y, return_counts=True)\n\nprint(np.asarray((unique, counts)))'

In [ ]:
'''sort_index = np.argsort(-counts)
counts = counts[sort_index]
unique = unique[sort_index]'''

'sort_index = np.argsort(-counts)\ncounts = counts[sort_index]\nunique = unique[sort_index]'

In [ ]:
'''cdf = np.cumsum(counts)
cdf = (cdf/len(y))*100
print(cdf)'''

'cdf = np.cumsum(counts)\ncdf = (cdf/len(y))*100\nprint(cdf)'

In [ ]:
'''cdf_index = list(range(0,len(cdf)))'''

'cdf_index = list(range(0,len(cdf)))'

In [ ]:
#np.argwhere(cdf>95)[0], np.argwhere(cdf>90)[0]

In [ ]:
'''plt.figure(figsize = (12,6))
plt.plot(cdf_index,cdf)
plt.axhline(95, c='red')
plt.axvline(2759, c='red')
plt.yticks(np.arange(0,101,5))
plt.xticks(np.arange(0,10000,500))
plt.show()'''

"plt.figure(figsize = (12,6))\nplt.plot(cdf_index,cdf)\nplt.axhline(95, c='red')\nplt.axvline(2759, c='red')\nplt.yticks(np.arange(0,101,5))\nplt.xticks(np.arange(0,10000,500))\nplt.show()"

In [ ]:
#len(unique)

In [ ]:
'''other_node_id = unique[2759:]
len(other_node_id)'''

'other_node_id = unique[2759:]\nlen(other_node_id)'

In [ ]:
'''with open('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/other_node_id.txt', 'a') as f:
  for node_id in other_node_id:
    f.write(f'{node_id},')'''

"with open('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/other_node_id.txt', 'a') as f:\n  for node_id in other_node_id:\n    f.write(f'{node_id},')"

In [ ]:
f = open('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/other_node_id.txt', 'r')

other_node_id = [int(i) for i in f.readline().split(',')[:-1]]

f.close()
print(other_node_id)

[15967, 3186, 15800, 8507, 31189, 12978, 32005, 588, 1386, 31871, 35508, 26655, 39381, 181727, 8846, 51359, 7331, 5347, 51174, 15698, 26940, 46786, 68849, 881, 8491, 16763, 1879, 31882, 22472, 25109, 40545, 22237, 420, 6035, 122852, 55588, 31956, 17956, 23117, 2467, 295, 85381, 11039, 10487, 46925, 78615, 103853, 59540, 8750, 17565, 18347, 450, 1831, 38762, 82027, 2830, 45510, 16720, 93129, 14776, 9103, 38214, 95704, 3699, 29897, 30003, 58087, 52086, 1245, 287, 7534, 363, 167904, 5418, 25573, 85585, 58783, 38176, 29856, 30478, 44409, 121775, 20705, 4527, 4493, 5067, 8198, 2121, 9496, 3097, 578, 3106, 7242, 102, 30642, 24074, 3255, 4135, 66550, 213026, 7057, 6653, 2408, 28876, 25444, 4372, 545, 15469, 15038, 39991, 51388, 32664, 138909, 107, 9766, 33225, 24813, 1993, 8722, 38562, 2577, 76398, 23925, 26398, 83642, 37520, 22996, 27486, 18298, 14905, 44828, 2547, 64855, 16919, 60488, 30062, 11921, 25094, 30520, 33368, 6983, 1737, 19341, 877, 6719, 78880, 31490, 47530, 102411, 551, 14768, 1

In [ ]:
other_node_id = np.array(other_node_id)
len(other_node_id)

7160

In [ ]:
Y = y.copy()
for i in tqdm(range(len(Y))):
  if Y[i] in other_node_id:
    Y[i] = -1

print(len(Y))

100%|██████████| 2868897/2868897 [00:20<00:00, 140017.12it/s]

2868897


In [ ]:
final_unique, final_counts = np.unique(Y, return_counts=True)

print(np.asarray((final_unique, final_counts)))
print(len(final_unique))

[[    -1      0      1 ... 166575 215592 267793]
 [143461   2984   1804 ...     95    114     94]]
2760


In [ ]:
number_of_classes = 2760

In [ ]:
'''final_sort_index = np.argsort(-final_counts)
final_counts = final_counts[final_sort_index]
final_unique = final_unique[final_sort_index]'''

'final_sort_index = np.argsort(-final_counts)\nfinal_counts = final_counts[final_sort_index]\nfinal_unique = final_unique[final_sort_index]'

In [ ]:
'''cdf = np.cumsum(final_counts)
cdf = (cdf/len(Y))*100

cdf_index = list(range(0,len(cdf)))
print(cdf)'''

'cdf = np.cumsum(final_counts)\ncdf = (cdf/len(Y))*100\n\ncdf_index = list(range(0,len(cdf)))\nprint(cdf)'

In [ ]:
'''plt.figure(figsize = (8,6))
plt.plot(cdf_index,cdf)

plt.yticks(np.arange(0,101,5))
plt.xticks(np.arange(0,3000,200))
plt.show()'''

'plt.figure(figsize = (8,6))\nplt.plot(cdf_index,cdf)\n\nplt.yticks(np.arange(0,101,5))\nplt.xticks(np.arange(0,3000,200))\nplt.show()'

# Preparing Data for modeling



```
>>> from sklearn import preprocessing
>>> le = preprocessing.LabelEncoder()
>>> le.fit([1, 2, 2, 6])
LabelEncoder()
>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])
```



In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [ ]:
len(x), len(Y)

(2868897, 2868897)

In [ ]:
x[:3],Y[:3]

(array(['pete cat bedtime blue doll inch pete cat coolest popular cat town new pete cat bedtime blue doll merrymaker rock striped red slipper one sleepy cat ready cuddle measure inch tall safe age removable clothing surface wash new pete cat bedtime blue plush doll based popular pete cat book james dean super cuddly ready naptime bedtime safe age perfect age measure inch merrymaker',
        'new yorker nyhm refrigerator magnet new yorker handsome cello wrapped hard magnet measure inch width inch height highlight one many beautiful new yorker cover full color cat tea cup new yorker cover artist gurbuz dogan eksioglu cat tea cup new yorker cover artist gurbuz dogan eksioglu handsome cello wrapped hard magnet ideal home office gift new yorker magazine lover highlight one many beautiful new yorker cover full color rigid magnet measure inch width inch height new yorker',
        'ultimate self sufficiency handbook complete guide baking craft gardening preserving harvest raising animal skyh

In [ ]:
number_of_classes = 2760

In [ ]:
le = LabelEncoder()
le.fit(Y)
Y = le.transform(Y)

In [ ]:
le.classes_

array([    -1,      0,      1, ..., 166575, 215592, 267793])

In [ ]:
keys = le.classes_
values = le.transform(keys)
label_encoder_mapping = dict(zip(keys, values))
print(label_encoder_mapping)

{-1: 0, 0: 1, 1: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 9: 8, 11: 9, 12: 10, 13: 11, 16: 12, 17: 13, 18: 14, 19: 15, 20: 16, 21: 17, 22: 18, 23: 19, 24: 20, 26: 21, 30: 22, 31: 23, 33: 24, 34: 25, 35: 26, 36: 27, 37: 28, 38: 29, 40: 30, 42: 31, 43: 32, 45: 33, 52: 34, 53: 35, 55: 36, 56: 37, 58: 38, 61: 39, 63: 40, 65: 41, 66: 42, 68: 43, 69: 44, 74: 45, 75: 46, 76: 47, 81: 48, 82: 49, 83: 50, 84: 51, 85: 52, 86: 53, 87: 54, 89: 55, 91: 56, 92: 57, 93: 58, 94: 59, 95: 60, 96: 61, 98: 62, 99: 63, 100: 64, 103: 65, 104: 66, 105: 67, 106: 68, 108: 69, 109: 70, 110: 71, 112: 72, 113: 73, 114: 74, 115: 75, 117: 76, 118: 77, 120: 78, 122: 79, 124: 80, 125: 81, 127: 82, 130: 83, 131: 84, 132: 85, 133: 86, 134: 87, 135: 88, 136: 89, 137: 90, 139: 91, 146: 92, 148: 93, 149: 94, 150: 95, 151: 96, 152: 97, 153: 98, 154: 99, 155: 100, 160: 101, 165: 102, 179: 103, 180: 104, 181: 105, 185: 106, 186: 107, 188: 108, 190: 109, 191: 110, 192: 111, 193: 112, 194: 113, 195: 114, 197: 115, 199: 116, 200: 117, 2

In [ ]:
# Save

np.save('label_encoder_mapping.npy', label_encoder_mapping) 



In [ ]:
# Load
read_dictionary = np.load('label_encoder_mapping.npy',allow_pickle='TRUE').item()
print(read_dictionary) 

{-1: 0, 0: 1, 1: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 9: 8, 11: 9, 12: 10, 13: 11, 16: 12, 17: 13, 18: 14, 19: 15, 20: 16, 21: 17, 22: 18, 23: 19, 24: 20, 26: 21, 30: 22, 31: 23, 33: 24, 34: 25, 35: 26, 36: 27, 37: 28, 38: 29, 40: 30, 42: 31, 43: 32, 45: 33, 52: 34, 53: 35, 55: 36, 56: 37, 58: 38, 61: 39, 63: 40, 65: 41, 66: 42, 68: 43, 69: 44, 74: 45, 75: 46, 76: 47, 81: 48, 82: 49, 83: 50, 84: 51, 85: 52, 86: 53, 87: 54, 89: 55, 91: 56, 92: 57, 93: 58, 94: 59, 95: 60, 96: 61, 98: 62, 99: 63, 100: 64, 103: 65, 104: 66, 105: 67, 106: 68, 108: 69, 109: 70, 110: 71, 112: 72, 113: 73, 114: 74, 115: 75, 117: 76, 118: 77, 120: 78, 122: 79, 124: 80, 125: 81, 127: 82, 130: 83, 131: 84, 132: 85, 133: 86, 134: 87, 135: 88, 136: 89, 137: 90, 139: 91, 146: 92, 148: 93, 149: 94, 150: 95, 151: 96, 152: 97, 153: 98, 154: 99, 155: 100, 160: 101, 165: 102, 179: 103, 180: 104, 181: 105, 185: 106, 186: 107, 188: 108, 190: 109, 191: 110, 192: 111, 193: 112, 194: 113, 195: 114, 197: 115, 199: 116, 200: 117, 2

In [ ]:
x = x[start:end]

Y = Y[start:end]


In [ ]:
X_train, X_val, y_train, y_val = train_test_split(x, Y, test_size=0.3, random_state=42)
print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(70000,)
(30000,)
(70000,)
(30000,)


#NLTK and Gensim

https://radimrehurek.com/gensim/models/word2vec.html

https://www.kaggle.com/pierremegret/gensim-word2vec-tutorial

In [ ]:
import gensim
import gensim.downloader
from gensim.models import KeyedVectors

In [ ]:
#list(gensim.downloader.info()['models'].keys())

In [ ]:
#word2vec_model = gensim.downloader.load('word2vec-google-news-300') 
#word2vec_model.save_word2vec_format('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/model.bin', binary=True)

In [ ]:
#model = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/wordvec.bin', binary=True)
#len(model.vocab)

In [ ]:
#!wget https://nlp.stanford.edu/data/glove.6B.zip

In [ ]:
#!unzip /content/glove.6B.zip

In [ ]:
'''# load the whole embedding into memory
glove_embeddings = dict()
f = open('/content/glove.6B.200d.txt')

for line in tqdm(f):
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    glove_embeddings[word] = coefs

f.close()
print('Loaded %s word vectors.' % len(glove_embeddings))'''

"# load the whole embedding into memory\nglove_embeddings = dict()\nf = open('/content/glove.6B.200d.txt')\n\nfor line in tqdm(f):\n    values = line.split()\n    word = values[0]\n    coefs = np.asarray(values[1:], dtype='float32')\n    glove_embeddings[word] = coefs\n\nf.close()\nprint('Loaded %s word vectors.' % len(glove_embeddings))"

In [ ]:
#np.save('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/glove_embeddings.npy', glove_embeddings) 

In [ ]:
glove_embeddings = np.load('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/glove_embeddings.npy',allow_pickle='TRUE').item()
print(len(glove_embeddings)) 

400000


# Modeling

In [ ]:
X_train = tf.data.Dataset.from_tensor_slices(X_train)
len(X_train)

70000

In [ ]:
X_val = tf.data.Dataset.from_tensor_slices(X_val)
len(X_val)

30000

In [ ]:
len(X_train)

70000

In [ ]:
len(y_train)

70000

In [ ]:
max_features = 50000  # Maximum vocab size.
max_len = 500  # Sequence length to pad the outputs to.
#embedding_dims = 2

In [ ]:
#vectorize_layer = TextVectorization(max_tokens=max_features, output_sequence_length=max_len)

In [ ]:
#vectorize_layer.adapt(X_train)

In [ ]:
'''import pickle

pickle.dump({'config': vectorize_layer.get_config(),
             'weights': vectorize_layer.get_weights()}
            , open("/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/vectorize_layer.pkl", "wb"))
'''

'import pickle\n\npickle.dump({\'config\': vectorize_layer.get_config(),\n             \'weights\': vectorize_layer.get_weights()}\n            , open("/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/vectorize_layer.pkl", "wb"))\n'

In [ ]:
import pickle
# `config` to create object and 
# `weights` to load the trained weights. 

from_disk = pickle.load(open("/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/vectorize_layer.pkl", "rb"))
vectorize_layer = TextVectorization.from_config(from_disk['config'])

# You have to call `adapt` with some dummy data (BUG in Keras)
vectorize_layer.adapt(tf.data.Dataset.from_tensor_slices(["xyz"]))

vectorize_layer.set_weights(from_disk['weights'])


In [ ]:
vectorize_layer.get_vocabulary()[:5]

['', '[UNK]', 'material']

In [ ]:
voc = vectorize_layer.get_vocabulary()            #max_features
word_index = dict(zip(voc, range(len(voc))))

print(len(voc))
print(len(word_index))

3
3


In [ ]:
num_tokens = max_features + 2
embedding_dim = 200
hits = 0
misses = 0

# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
    embedding_vector = glove_embeddings.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
    else:
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

Converted 1 words (2 misses)


In [ ]:
embedding_matrix.shape

(50002, 200)

In [ ]:
from tensorflow.keras import layers
from keras.models import Sequential
import keras
from tensorflow.keras.layers import Embedding

In [ ]:
'''
embedding_layer = Embedding(
    num_tokens,
    embedding_dim,
    weights=[embedding_matrix],
    trainable=False)
'''

'\nembedding_layer = Embedding(\n    num_tokens,\n    embedding_dim,\n    weights=[embedding_matrix],\n    trainable=False)\n'

In [ ]:
'''
model = Sequential()
 
model.add(keras.Input(shape=(None,), dtype="int64"))
#model.add(tf.keras.Input(shape=(1,), dtype=tf.string))
 
 
#embedding layer
model.add(embedding_layer)
 
#lstm layer
model.add(layers.LSTM(256,return_sequences=True))
model.add(layers.Dropout(0.2))
 
#Global Maxpooling
model.add(layers.GlobalMaxPooling1D())
 
#Dense Layer
model.add(layers.Dense(128,activation='relu')) 
model.add(layers.Dropout(0.2))
 
#Dense Layer
model.add(layers.Dense(128,activation='relu')) 
model.add(layers.Dropout(0.2))
 
model.add(layers.Dense(64,activation='relu')) 
model.add(layers.Dense(number_of_classes,activation='sigmoid'))
 
 
print(model.summary())
'''

'\nmodel = Sequential()\n \nmodel.add(keras.Input(shape=(None,), dtype="int64"))\n#model.add(tf.keras.Input(shape=(1,), dtype=tf.string))\n \n \n#embedding layer\nmodel.add(embedding_layer)\n \n#lstm layer\nmodel.add(layers.LSTM(256,return_sequences=True))\nmodel.add(layers.Dropout(0.2))\n \n#Global Maxpooling\nmodel.add(layers.GlobalMaxPooling1D())\n \n#Dense Layer\nmodel.add(layers.Dense(128,activation=\'relu\')) \nmodel.add(layers.Dropout(0.2))\n \n#Dense Layer\nmodel.add(layers.Dense(128,activation=\'relu\')) \nmodel.add(layers.Dropout(0.2))\n \nmodel.add(layers.Dense(64,activation=\'relu\')) \nmodel.add(layers.Dense(number_of_classes,activation=\'sigmoid\'))\n \n \nprint(model.summary())\n'

In [ ]:
model = keras.models.load_model('/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/model_4.h5')
print(model.summary)

ValueError: ignored

In [ ]:
for i in X_train.take(3):
  print(i.numpy())

In [ ]:
for i in X_train.take(1):
  print(i.numpy())

In [ ]:
X_TRAIN = vectorize_layer([i.numpy() for i in X_train])
X_VAL = vectorize_layer([i.numpy() for i in X_val])
 
Y_TRAIN = np.array(y_train)
Y_VAL = np.array(y_val)

In [ ]:
print(X_TRAIN.shape)
print(X_VAL.shape)
print(Y_TRAIN.shape)
print(Y_VAL.shape)

In [ ]:
from keras.optimizers import Adam
opt = Adam()
 
model.compile(loss="sparse_categorical_crossentropy", optimizer=opt, metrics=["acc"])
 
filepath = "/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/model_epoch_{epoch:08d}.h5"
checkpoint = keras.callbacks.ModelCheckpoint(filepath, save_best_only= False)
 
callbacks = [checkpoint]

In [ ]:
for i in range(1,epochs+1):
  model.fit(X_TRAIN, Y_TRAIN, batch_size= 64, epochs=i, validation_data=(X_VAL, Y_VAL))
  try:
    model.save(f'/content/drive/MyDrive/Datasets/Amazon_ML_Challenge/model_{i+4}.h5')
  except:
    pass
  print('Success:',i)

# END